export { routes as authRoutes } from "./auth.routes";
export { routes as facultyRoutes } from "./faculty.routes";
export { routes as departmentRoutes } from "./department.routes";
export { routes as teacherRoutes } from "./teacher.routes";
export { routes as subjectRoutes } from "./subject.routes";
export { routes as evaluationRoutes } from "./evaluation-form.routes";
export { routes as questionRoutes } from "./question.routes";
export { routes as AnswerRoutes } from "./answer.routes";
export { routes as ReportRoutes } from "./report.routes";
