export * from "./user.service";
export * from "./faculty.service";
export * from "./department.service";
export * from "./teacher.service";
export * from "./subject.service";
export * from "./evaluation-form.service";
export * from "./question.service";
export * from "./answer.service";
export * from "./reports/report.service";
